package xpenst_version.Database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.*;

import xpenst_version.Model.Expense;

public class expnseDao {
    //to save expense
    public void saveExp(Expense exps){
        try{
            Connection conn = DataConnections.getConnection();
            String sql = "Insert INTO expenses( item, amount, category, expense_date, expense_time) VALUES (?,?,?,?,?)";
            PreparedStatement pstat = conn.prepareStatement(sql);
            
            pstat.setString(1, exps.getItem());
            pstat.setDouble(2,exps.getAmount());
            pstat.setString(3,exps.getCategory());
            pstat.setDate(4,java.sql.Date.valueOf(exps.getDate()));
            pstat.setTime(5,java.sql.Time.valueOf(exps.getTime()));
            pstat.executeUpdate();
            System.out.println("Expense Added Succesfully");
        }
        catch(SQLException e) {
             System.out.println("Expense not added" + e.getMessage());
        }
    }
    // to view all expenses 
    public List<Expense> view_all(){
        List<Expense> list = new ArrayList<>();
        String history_sql = "Select * from expenses";
        try (Connection conn = DataConnections.getConnection();
            PreparedStatement pstat = conn.prepareStatement(history_sql)){ // used to create a statement object to run sql 

            java.sql.ResultSet rs = pstat.executeQuery(); //ResultSet is inbuilt to fetch table like object 
            //executeQuery --  execute sql select statement 

            while(rs.next()){// .next means go to next row 
                    Expense sqexp = new Expense(
                        rs.getDouble("amount"),
                        rs.getString("item"),
                        rs.getString("category"),
                        rs.getDate("expense_date").toLocalDate(),
                        rs.getTime("expense_time").toLocalTime()
                    );
                    list.add(sqexp);
            }

        } catch (SQLException e) {
            System.out.println("Cannot view all the expenses");
        }
        return list;
    }
    // to delete a expense 
    public void deleteRecord(int id){
        String delete_sql = " delete from expenses where id = ?";
        try(Connection conn = DataConnections.getConnection();
        PreparedStatement pstat = conn.prepareStatement(delete_sql)){
        pstat.setInt(1,id);

        int deletedrow = pstat.executeUpdate();
        if(deletedrow>0){
            System.out.println("Expense deleted successfully ");
        }else{
            System.out.println("No record found");
        }
    }catch(SQLException e){
    System.out.println("Error" + e.getMessage());
    }
}
    //to update an existing expense 
    public void UpdateExpense(Expense uexp, int id){
        String sql = "Update expenses Set item = ?, amount = ?, category = ?, expense_date = ?, expense_time = ? WHERE id = ?";
        try(Connection conn = DataConnections.getConnection();
        PreparedStatement pstat = conn.prepareStatement(sql)){
            
            
            pstat.setString(1,uexp.getItem());
            pstat.setDouble(2,uexp.getAmount());
            pstat.setString(3,uexp.getCategory());
            pstat.setDate(4,java.sql.Date.valueOf(uexp.getDate()));
            pstat.setTime(5,java.sql.Time.valueOf(uexp.getTime()));
            pstat.setInt(6,id);
            int rows = pstat.executeUpdate();

            if(rows>0){
                System.out.println(rows + " Updated Successfully");
            }else{
                System.out.println("No row found with this ID");
            }
            
        } catch (SQLException e) {
            System.out.println("Unable to Update the expense");
        }
    }
    // to find sum of expense (day, month, year)
    public void sum_expense(int option, int value){
        String sql= "";
        switch(option){
        case 1 ->{
            sql = "Select sum(amount) from expenses where day(expense_date) = ?";
        }
        case 2 -> {
            sql = "Select sum(amount) from expenses where month(expense_date) = ?";
        }
        case 3 -> {
            sql = "Select sum(amount) from expenses where year(expense_date) = ?";
        }
        default -> {
            System.out.println("Invalid Option");
            return; 
        }
        }
        try(Connection conn = DataConnections.getConnection();
        PreparedStatement pstat = conn.prepareStatement(sql)){
            pstat.setInt(1,value);
            java.sql.ResultSet rs =pstat.executeQuery(); //Result holds the table that is generated by the MYsql 

            if(rs.next()){ // rs.next to move to new row its like a loop up until it finds the data it shows it and when not it breaks and stops 
               double total =  rs.getDouble(1);
               if( total == 0 ){
                System.out.println("No expense is found");
               }else{
                System.out.println("Total Expense Rs. " + total);
               }
            }
        }catch(SQLException e){
            System.out.println("Error finding the expense");
        }
        }
}

