spring.application.name=Xpensto
spring.datasource.url = "jdbc:mysql://localhost:3306/xpenst_db"
spring.datasource.username = "root"
spring.datasource.password = "san2772"
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#create update table based on entity
spring.jpa.hibernate.ddl-auto = update  
# to show sql queries in the console so we can see what spring is doing
spring.jpa.show-sql = true
# make sql format easy to read
spring.jpa.properties.hibernate.format_sql=true
# helps hibernate generate mysql
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect